export const definedContracts = ["Pasha Bank", "Kapital Bank", "Bank of Baku"];

export const definedQuestions = [
  "How can I track my transactions?",
  "Can I upload files like receipts in the app?",
  "How do I manage contracts and invoices?",
  "What security measures protect my data?",
];

export const definedContactSubjects = [
  "Account Inquiry",
  "Transaction Issue",
  "Card Replacement",
  "Loan Application",
  "Fraud Report",
  "Technical Support",
  "Feedback and Suggestions",
  "Account Closure",
  "Payment Assistance",
  "Security Concerns",
  "ATM-related Query",
  "Interest Rates",
  "Lost/Stolen Card",
  "General Inquiry",
];

export const publicPaths = [
  "/signin",
  "/signup",
  "/forget-password",
  "/terms-privacy",
  "/az/signin",
  "/az/forget-password",
  "/az/terms-privacy",
  "/en/signup",
  "/az/signup",
  "/en/signin",
  "/en/forget-password",
  "/en/terms-privacy",
];

export const restrictedPaths = [
  "/",
  "/en",
  "/az",
  "/en/invoices",
  "/en/chatbot",
  "/az/chatbot",
  "/en/contact",
  "/az/contact",
  "/en/cards",
  "/en/contracts",
  "/en/documents",
  "/en/insurance",
  "/en/invoices",
  "/en/settings",
  "/en/transactions",
  "/az/invoices",
  "/az/cards",
  "/en/contact",
  "/az/contracts",
  "/az/documents",
  "/az/insurance",
  "/az/invoices",
  "/az/settings",
  "/az/contact",
  "/az/transactions",
  "/invoices",
  "/cards",
  "/contracts",
  "/documents",
  "/insurance",
  "/invoices",
  "/settings",
  "/contact",
  "/transactions",
  "/en/contracts/create",
];

export const matcher = [
  "/",
  "/en",
  "/az",
  "/en/invoices",
  "/en/cards",
  "/en/contracts",
  "/en/chatbot",
  "/az/chatbot",
  "/en/contact",
  "/az/contact",
  "/en/documents",
  "/en/insurance",
  "/en/invoices",
  "/en/settings",
  "/en/transactions",
  "/en/contact",
  "/az/invoices",
  "/az/cards",
  "/az/contracts",
  "/az/documents",
  "/az/insurance",
  "/az/invoices",
  "/az/settings",
  "/az/contact",
  "/az/transactions",
  "/invoices",
  "/cards",
  "/contact",
  "/contracts",
  "/documents",
  "/insurance",
  "/invoices",
  "/settings",
  "/transactions",
  "/en/contracts/create",
  "/signin",
  "/signup",
  "/forget-password",
  "/en/signin",
  "/en/forget-password",
  "/en/signup",
  "/az/signin",
  "/az/signup",
  "/az/forget-password",
  "/terms-privacy",
  "/az/terms-privacy",
  "/en/terms-privacy",
  "/((?!(?:az|en|api|_next/static|_next/image)(?:/|$))(?!.*\\.[^.]*$).*/?)",
];
