export const activeContracts = [
  {
    id: 1,
    companyImg: "/assets/contracts/bankOfBaku.jpg",
    company: "Bank of Baku",
    companyLocation: "Azerbaijan",
    amount: "5000",
    clientName: "Emmanuel Fransisco",
    startDate: "March 1st, 2022",
    endDate: " April 1st, 2022",
  },
  {
    id: 2,
    companyImg: "/assets/contracts/pashaBank.jpg",
    company: "Pasha Bank",
    companyLocation: "Azerbaijan",
    amount: "5000",
    clientName: "Jayden Harris",
    startDate: "March 1st, 2022",
    endDate: " April 1st, 2022",
  },
  {
    id: 3,
    companyImg: "/assets/contracts/kapitalBank.png",
    company: "Kapital Bank",
    companyLocation: "Azerbaijan",
    amount: "5000",
    clientName: "Maria Nicholson",
    startDate: "March 1st, 2022",
    endDate: " April 1st, 2022",
  },
  {
    id: 4,
    companyImg: "/assets/contracts/pashaBank.jpg",
    company: "Pasha Bank",
    companyLocation: "Azerbaijans",
    amount: "5000",
    clientName: "Emmanuel Fransisco",
    startDate: "March 1st, 2022",
    endDate: " April 1st, 2022",
  },
];

export const contractClients = [
  {
    id: 1,
    clientImg: "/assets/contracts/client1.png",
    clientName: "Chloe Wallows",
    clientCompany: "Saphore Inc.",
  },
  {
    id: 2,
    clientImg: "/assets/contracts/client2.png",
    clientName: "Chloe Wallows",
    clientCompany: "Saphore Inc.",
  },
  {
    id: 3,
    clientImg: "/assets/contracts/client3.png",
    clientName: "Chloe Wallows",
    clientCompany: "Saphore Inc.",
  },
  {
    id: 4,
    clientImg: "/assets/contracts/client4.png",
    clientName: "Chloe Wallows",
    clientCompany: "Saphore Inc.",
  },
  {
    id: 5,
    clientImg: "/assets/contracts/client5.png",
    clientName: "Chloe Wallows",
    clientCompany: "Saphore Inc.",
  },
  {
    id: 6,
    clientImg: "/assets/contracts/client1.png",
    clientName: "Chloe Wallows",
    clientCompany: "Saphore Inc.",
  },
  {
    id: 7,
    clientImg: "/assets/contracts/client2.png",
    clientName: "Chloe Wallows",
    clientCompany: "Saphore Inc.",
  },
  {
    id: 8,
    clientImg: "/assets/contracts/client3.png",
    clientName: "Chloe Wallows",
    clientCompany: "Saphore Inc.",
  },
  {
    id: 9,
    clientImg: "/assets/contracts/client4.png",
    clientName: "Chloe Wallows",
    clientCompany: "Saphore Inc.",
  },
  {
    id: 10,
    clientImg: "/assets/contracts/client5.png",
    clientName: "Chloe Wallows",
    clientCompany: "Saphore Inc.",
  },
];
