export const transactionsHistory = [
  {
    id: 1,
    personName: "Chloe Wallows",
    personImg: "/assets/transactions/p1.png",
    company: "Saphore Inc.",
    paymentDate: "Mar 1, 2023",
    paymentHour: "08:00 AM",
    paymentMethodUrl: "/assets/transactions/paypal.png",
    paymentTitle: "PayPal",
    paidDate: "1 Jun 2023",
    price: "1,546",
  },
  {
    id: 2,
    personName: "Chloe Wallows",
    personImg: "/assets/transactions/p2.png",
    company: "Saphore Inc.",
    paymentDate: "Mar 1, 2023",
    paymentHour: "08:00 AM",
    paymentMethodUrl: "/assets/transactions/paypal.png",
    paymentTitle: "PayPal",
    paidDate: "1 Jun 2023",
    price: "1,546",
  },
  {
    id: 3,
    personName: "Chloe Wallows",
    personImg: "/assets/transactions/p3.png",
    company: "Saphore Inc.",
    paymentDate: "Mar 1, 2023",
    paymentHour: "08:00 AM",
    paymentMethodUrl: "/assets/transactions/paypal.png",
    paymentTitle: "PayPal",
    paidDate: "1 Jun 2023",
    price: "1,546",
  },
  {
    id: 4,
    personName: "Chloe Wallows",
    personImg: "/assets/transactions/p4.png",
    company: "Saphore Inc.",
    paymentDate: "Mar 1, 2023",
    paymentHour: "08:00 AM",
    paymentMethodUrl: "/assets/transactions/paypal.png",
    paymentTitle: "PayPal",
    paidDate: "1 Jun 2023",
    price: "1,546",
  },
  {
    id: 5,
    personName: "Chloe Wallows",
    personImg: "/assets/transactions/p5.png",
    company: "Saphore Inc.",
    paymentDate: "Mar 1, 2023",
    paymentHour: "08:00 AM",
    paymentMethodUrl: "/assets/transactions/paypal.png",
    paymentTitle: "PayPal",
    paidDate: "1 Jun 2023",
    price: "1,546",
  },
];
