export const transactionsHistory = [
  {
    id: 1,
    personName: "Chloe Wallows",
    personImg: "/assets/transactions/p1.png",
    company: "Saphore Inc.",
    paymentDate: "Mar 1, 2023",
    paymentHour: "08:00 AM",
    paymentMethodUrl: "/assets/transactions/paypal.png",
    paymentTitle: "PayPal",
    paidDate: "1 Jun 2023",
    price: 1546,
  },
  {
    id: 2,
    personName: "Bowen Higgins",
    personImg: "/assets/transactions/p2.png",
    company: "Saphore Inc.",
    paymentDate: "Mar 1, 2023",
    paymentHour: "08:00 AM",
    paymentMethodUrl: "/assets/transactions/paypal.png",
    paymentTitle: "PayPal",
    paidDate: "1 Jun 2023",
    price: 2413,
  },
  {
    id: 3,
    personName: "Franklin Sierra",
    personImg: "/assets/transactions/p3.png",
    company: "Saphore Inc.",
    paymentDate: "Mar 1, 2023",
    paymentHour: "08:00 AM",
    paymentMethodUrl: "/assets/transactions/paypal.png",
    paymentTitle: "PayPal",
    paidDate: "1 Jun 2023",
    price: 5221,
  },
  {
    id: 4,
    personName: "Leighton Kram",
    personImg: "/assets/transactions/p4.png",
    company: "Saphore Inc.",
    paymentDate: "Mar 1, 2023",
    paymentHour: "08:00 AM",
    paymentMethodUrl: "/assets/transactions/paypal.png",
    paymentTitle: "PayPal",
    paidDate: "1 Jun 2023",
    price: 1421,
  },
  {
    id: 5,
    personName: "Amelie Griffith",
    personImg: "/assets/transactions/p5.png",
    company: "Saphore Inc.",
    paymentDate: "Mar 1, 2023",
    paymentHour: "08:00 AM",
    paymentMethodUrl: "/assets/transactions/paypal.png",
    paymentTitle: "PayPal",
    paidDate: "1 Jun 2023",
    price: 3112,
  },
];
